import os
# CRITICAL FOR VERCEL: Force matplotlib to use /tmp for caching and use headless backend
os.environ["MPLCONFIGDIR"] = "/tmp"
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

import re, textwrap, tempfile, subprocess, base64, io, zipfile, urllib.request, urllib.parse
import xml.etree.ElementTree as ET
import time
import json
import pandas as pd
import jinja2
from google import genai
from flask import Flask, render_template, request, jsonify

app = Flask(__name__)

# =============================================================================
# CONSTANTS & CONFIG
# =============================================================================
GEMINI_MODEL = "gemini-2.5-flash" # Adjusted for current SDK compatibility

SECTION_TAGS = [
    "ABSTRACT", "INTRODUCTION", "RELATED_WORK", "METHODOLOGY",
    "RESULTS_AND_ANALYSIS", "DISCUSSION", "CONCLUSION", "ACKNOWLEDGEMENTS",
]

WORDS_PER_PAGE_SINGLE = 450
WORDS_PER_PAGE_DOUBLE = 600

SECTION_WEIGHT = {
    "ABSTRACT": 0.05, "INTRODUCTION": 0.16, "RELATED_WORK": 0.14,
    "METHODOLOGY": 0.22, "RESULTS_AND_ANALYSIS": 0.20, "DISCUSSION": 0.12,
    "CONCLUSION": 0.07, "ACKNOWLEDGEMENTS": 0.04,
}

LATEX_TMPL = r"""
\documentclass[11pt[% if two_col %],twocolumn[% endif %]]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{lmodern}
\usepackage{microtype}
\usepackage{amsmath,amssymb,amsfonts,mathtools,bm}
\usepackage[
[% if two_col %]
    letterpaper,top=0.9in,bottom=0.9in,left=0.65in,right=0.65in,columnsep=18pt,
[% else %]
    letterpaper,top=1in,bottom=1in,left=1.1in,right=1.1in,
[% endif %]
]{geometry}
\usepackage{graphicx,booktabs,tabularx,multirow,array,float}
\usepackage[numbers,sort&compress]{natbib}
\usepackage{hyperref,url}
\hypersetup{colorlinks=true,linkcolor=blue!65!black,citecolor=green!55!black,urlcolor=blue!75!black,
    pdftitle={[[ escaped_title ]]},pdfauthor={[[ first_author ]]},pdfkeywords={[[ escaped_kw ]]}}
\usepackage{parskip,setspace,titlesec,abstract,authblk,fancyhdr,xcolor,soul}
\usepackage{algorithm,algpseudocode}
\titleformat{\section}{\large\bfseries\scshape}{}{0em}{}[\vspace{-2pt}\rule{\linewidth}{0.5pt}\vspace{2pt}]
\titleformat{\subsection}{\normalsize\bfseries}{}{0em}{}
\titlespacing*{\section}{0pt}{14pt}{6pt}
\titlespacing*{\subsection}{0pt}{10pt}{4pt}
\pagestyle{fancy}\fancyhf{}
\renewcommand{\headrulewidth}{0.35pt}
\fancyhead[L]{\small\scshape\textcolor{gray}{[[ short_title ]]}}
\fancyhead[R]{\small\textcolor{gray}{\thepage}}
\fancyfoot[C]{\small\textcolor{gray!60}{Generated by SciWrite AI \textperiodcentered{} \today}}
\renewcommand{\abstractname}{\normalsize\bfseries\scshape Abstract}
\setlength{\absleftindent}{0pt}\setlength{\absrightindent}{0pt}
\title{\vspace{-1.5em}\Large\bfseries [[ escaped_title ]]%
[% if kw_raw %]\\\vspace{0.3em}\normalsize\normalfont\textit{Keywords:}\ \small [[ escaped_kw ]][% endif %]}
[% for a in authors %]
\author[[[ loop.index ]]]{\textbf{[[ a.name ]]}[% if a.email %]\thanks{\href{mailto:[[ a.email ]]}{[[ a.email ]]}}\vspace{-0.5em}[% endif %]}
\affil[[[ loop.index ]]]{\small\textit{[[ a.affil ]]}}
[% endfor %]
\date{\today}
\begin{document}
\maketitle\thispagestyle{fancy}
\begin{abstract}\noindent [[ sec.ABSTRACT ]]\end{abstract}
[% if two_col %]\vspace{0.5em}\noindent\rule{\linewidth}{0.3pt}\vspace{0.2em}[% endif %]
\section{Introduction}
[[ sec.INTRODUCTION ]]
\section{Related Work}
[[ sec.RELATED_WORK ]]
\section{Methodology}
[[ sec.METHODOLOGY ]]
[% if figs %]
[% for f in figs %]
\begin{figure}[ht]\centering
\includegraphics[width=0.95\linewidth]{[[ f.fn ]]}
\caption{[[ f.cap ]]}\label{fig:[[ loop.index ]]}
\end{figure}
[% endfor %]
[% endif %]
\section{Results and Analysis}
[[ sec.RESULTS_AND_ANALYSIS ]]
\section{Discussion}
[[ sec.DISCUSSION ]]
\section{Conclusion}
[[ sec.CONCLUSION ]]
\section*{Acknowledgements}
[[ sec.ACKNOWLEDGEMENTS ]]
[% if bibtex %]
\begin{filecontents*}{\jobname.bib}
[[ bibtex ]]
\end{filecontents*}
\bibliographystyle{unsrtnat}
\bibliography{\jobname}
[% endif %]
\end{document}
"""

# =============================================================================
# UTILITIES
# =============================================================================
def escape_for_latex(text: str) -> str:
    if not isinstance(text, str): text = str(text)
    replacements = {
        "\\": r"\textbackslash{}", "&": r"\&", "%": r"\%", "$": r"\$",
        "#": r"\#", "_": r"\_", "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}", "^": r"\textasciicircum{}"
    }
    for k, v in replacements.items():
        text = text.replace(k, v)
    return text

def compute_section_targets(pages: int, two_col: bool) -> dict:
    wpp = WORDS_PER_PAGE_DOUBLE if two_col else WORDS_PER_PAGE_SINGLE
    total = pages * wpp
    return {tag: max(80, int(total * w)) for tag, w in SECTION_WEIGHT.items()}

def fetch_arxiv_literature(query: str, max_results: int = 8) -> tuple[str, str]:
    if not query.strip(): query = "machine learning"
    safe_query = urllib.parse.quote(query)
    url = f"https://export.arxiv.org/api/query?search_query=all:{safe_query}&start=0&max_results={max_results}&sortBy=relevance"
    bibtex_entries, abstract_summaries = [], []
    try:
        with urllib.request.urlopen(url, timeout=10) as response:
            xml_data = response.read()
        root = ET.fromstring(xml_data)
        ns = {'atom': 'http://www.w3.org/2005/Atom'}
        for entry in root.findall('atom:entry', ns):
            title = entry.find('atom:title', ns).text.replace('\n', ' ').strip()
            summary = entry.find('atom:summary', ns).text.replace('\n', ' ').strip()
            published = entry.find('atom:published', ns).text[:4]
            authors = [a.find('atom:name', ns).text for a in entry.findall('atom:author', ns)]
            author_str = " and ".join(authors)
            last_name = authors[0].split()[-1].lower() if authors else "unknown"
            first_word = re.sub(r'[^a-zA-Z0-9]', '', title.split()[0].lower())
            cite_key = f"{last_name}{published}{first_word}"
            bibtex = textwrap.dedent(f"""
            @article{{{cite_key},
              title={{{title}}}, author={{{author_str}}}, journal={{arXiv preprint}}, year={{{published}}}
            }}""").strip()
            bibtex_entries.append(bibtex)
            abstract_summaries.append(f"[{cite_key}] {title} ({published}): {summary}")
        return "\n\n".join(bibtex_entries), "\n\n".join(abstract_summaries)
    except Exception:
        return "", ""

# =============================================================================
# AI & GENERATION LOGIC
# =============================================================================
def call_gemini_with_retry(api_key: str, prompt: str, retries: int = 3) -> str:
    client = genai.Client(api_key=api_key)
    for attempt in range(retries):
        try:
            res = client.models.generate_content(
                model=GEMINI_MODEL, contents=prompt,
                config=genai.types.GenerateContentConfig(temperature=0.2)
            )
            return res.text
        except Exception as e:
            if "503" in str(e) or "429" in str(e):
                if attempt < retries - 1:
                    time.sleep(2 ** attempt)
                    continue
            raise e
    return ""

def clean_llm_latex_output(raw_output: str) -> str:
    clean_text = raw_output.strip()
    if clean_text.startswith("```"):
        clean_text = re.sub(r'^```[a-zA-Z]*\n', '', clean_text)
        clean_text = re.sub(r'\n```$', '', clean_text)
    return clean_text.strip()

def generate_academic_chart(api_key: str, paper_title: str, results_notes: str, figure_index: int) -> tuple[str, bytes]:
    client = genai.Client(api_key=api_key)
    # Use /tmp for serverless compatibility
    chart_filename = f"/tmp/generated_chart_{figure_index}.png"
    base_name = f"generated_chart_{figure_index}.png"
    
    prompt = f"""
    You are an expert Data Scientist. Write an isolated Python script using matplotlib to generate a chart.
    Title: {paper_title}
    Data: {results_notes}
    Save Path: '{chart_filename}'
    CRITICAL: Output ONLY raw python code. Use plt.savefig('{chart_filename}', dpi=300, bbox_inches='tight'). Use plt.close('all').
    """
    try:
        res = client.models.generate_content(model=GEMINI_MODEL, contents=prompt,
            config=genai.types.GenerateContentConfig(temperature=0.1))
        clean_code = res.text.strip().replace("```python", "").replace("```", "")
        
        local_scope = {"plt": plt, "pd": pd, "re": re}
        plt.close('all')
        exec(clean_code, globals(), local_scope)
        
        if os.path.exists(chart_filename):
            with open(chart_filename, "rb") as f:
                img_bytes = f.read()
            os.remove(chart_filename)
            plt.close('all')
            return base_name, img_bytes
    except Exception:
        plt.close('all')
    return None

def make_jinja_env() -> jinja2.Environment:
    return jinja2.Environment(
        block_start_string="[%", block_end_string="%]",
        variable_start_string="[[", variable_end_string="]]",
        comment_start_string="[#", comment_end_string="#]",
        trim_blocks=True, lstrip_blocks=True, autoescape=False
    )

def render_latex(title, authors_list, two_col, keywords, sections, bibtex, figs=None):
    env = make_jinja_env()
    tmpl = env.from_string(LATEX_TMPL)
    escaped_authors = []
    first_author = ""
    for a in authors_list:
        if not a.get("name"): continue
        if not first_author: first_author = escape_for_latex(a["name"])
        escaped_authors.append({
            "name": escape_for_latex(a["name"]),
            "affil": escape_for_latex(a.get("affil", "")),
            "email": escape_for_latex(a.get("email", ""))
        })
    short = (title[:52]+"...") if len(title) > 55 else title
    return tmpl.render(
        escaped_title=escape_for_latex(title), short_title=escape_for_latex(short),
        first_author=first_author, escaped_kw=escape_for_latex(keywords), kw_raw=keywords.strip(),
        authors=escaped_authors, two_col=two_col, sec=sections, bibtex=bibtex.strip(), figs=figs or []
    )

def generate_overleaf_zip(latex_src: str, bibtex_data: str, uploaded_figs: list, generated_figs: list) -> bytes:
    zip_buffer = io.BytesIO()
    with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zip_file:
        zip_file.writestr("main.tex", latex_src)
        if bibtex_data.strip():
            zip_file.writestr("references.bib", bibtex_data.strip())
        for uf in uploaded_figs:
            safe_name = re.sub(r"[^\w.\-]", "_", uf['filename'])
            zip_file.writestr(safe_name, uf['data'])
        for filename, img_bytes in generated_figs:
            zip_file.writestr(filename, img_bytes)
    return zip_buffer.getvalue()

# =============================================================================
# ROUTES
# =============================================================================
@app.route('/')
def index():
    return render_template('index.html')

@app.route('/api/generate', methods=['POST'])
def generate():
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        return jsonify({"error": "GEMINI_API_KEY environment variable not set on server."}), 500

    try:
        # Parse text fields
        title = request.form.get('title', '')
        keywords = request.form.get('keywords', '')
        authors_json = request.form.get('authors', '[]')
        authors_list = json.loads(authors_json)
        
        abstract_goals = request.form.get('abstract_goals', '')
        intro_bg = request.form.get('intro_bg', '')
        methodology_notes = request.form.get('methodology_notes', '')
        results_data = request.form.get('results_data', '')
        extra_notes = request.form.get('extra_notes', '')
        bibtex_entries = request.form.get('bibtex_entries', '')
        
        layout_opt = request.form.get('layout_opt', 'Single Column')
        two_col = layout_opt == 'Double Column'
        target_pages = int(request.form.get('target_pages', 8))
        
        # Parse uploaded files
        uploaded_figs = []
        for file in request.files.getlist('figures'):
            if file.filename:
                uploaded_figs.append({'filename': file.filename, 'data': file.read()})

        # 1. Literature
        search_query = f"{title} {keywords}"
        real_bibtex, arxiv_summaries = fetch_arxiv_literature(search_query, max_results=6)
        combined_bibtex = f"{bibtex_entries}\n\n{real_bibtex}".strip()

        # 2. Charts
        generated_charts_list = []
        for idx in range(1, 3):
            chart_asset = generate_academic_chart(api_key, title, results_data, idx)
            if chart_asset: generated_charts_list.append(chart_asset)

        # 3. Sections
        sections_dict = {}
        compiled_user_notes = f"Abstract: {abstract_goals}\nIntro: {intro_bg}\nMethod: {methodology_notes}\nResults: {results_data}\nExtra: {extra_notes}"
        sec_targets = compute_section_targets(target_pages, two_col)
        
        cite_keys = re.findall(r"@\w+\{(\w+),", combined_bibtex)
        cite_str = ", ".join(cite_keys) if cite_keys else "(none)"

        for tag in SECTION_TAGS:
            history = "PREVIOUS SECTIONS:\n" + "".join([f"---{k}---\n{v[:300]}...\n" for k,v in sections_dict.items()]) if sections_dict else ""
            prompt = textwrap.dedent(f"""
            You are writing ONE section of a research paper.
            TITLE: {title} | SECTION: {tag} | WORDS: ~{sec_targets.get(tag, 300)}
            CONTEXT: {arxiv_summaries} | KEYS: {cite_str}
            NOTES: {compiled_user_notes} | {history}
            Write ONLY the '{tag}' section body in LaTeX prose. No headers.
            """)
            raw_text = call_gemini_with_retry(api_key, prompt)
            sections_dict[tag] = clean_llm_latex_output(raw_text)

        # 4. Render & Package
        fig_list = [{"fn": re.sub(r"[^\w.\-]", "_", f['filename']), "cap": f.get('filename')} for f in uploaded_figs]
        fig_list.extend([{"fn": fn, "cap": "Generated plot"} for fn, _ in generated_charts_list])
        
        latex_src = render_latex(title, authors_list, two_col, keywords, sections_dict, combined_bibtex, fig_list)
        zip_payload = generate_overleaf_zip(latex_src, combined_bibtex, uploaded_figs, generated_charts_list)
        
        wcs = {t: len(v.split()) for t, v in sections_dict.items()}
        total_words = sum(wcs.values())

        return jsonify({
            "success": True,
            "latex_src": latex_src,
            "zip_base64": base64.b64encode(zip_payload).decode('utf-8'),
            "sections": sections_dict,
            "word_counts": wcs,
            "total_words": total_words
        })

    except Exception as e:
        return jsonify({"error": str(e)}), 500

if __name__ == '__main__':
    app.run(debug=True, port=5000)